when@dev:
    web_profiler:
        toolbar: '%kernel.debug%'

    framework:
        profiler:
            collect: '%kernel.debug%'
            collect_serializer_data: '%kernel.debug%'

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
