services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:rw
      - composer_cache:/tmp/composer
    environment:
      APP_ENV: dev
      APP_SECRET: change-me-in-env-local
      DEFAULT_URI: http://localhost:8080
      DATABASE_URL: postgresql://app:app@database:5432/app?serverVersion=16&charset=utf8
      MAILER_DSN: smtp://mailpit:1025
    depends_on:
      database:
        condition: service_healthy
      mailpit:
        condition: service_started
    ports:
      - "8080:8000"
    command: ["sh", "docker/entrypoint.sh"]

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d app -U app"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  database_data:
  composer_cache:
